### ISSUE TITLE
Rebase on supported openshift openjdk image

### ISSUE THREAD

**Issue by lpsantil** [pylejowdmn/springboot-gradle-s2i#1]
See the image redhat-openjdk-18/openjdk18-openshift at https://registry.access.redhat.com or https://github.com/redhat-helloworld-msa/ola for examples, or, https://access.redhat.com/documentation/en-us/red_hat_jboss_middleware_for_openshift/3/html-single/red_hat_java_s2i_for_openshift/.

This will increase the supportability of derived images and apps.  Run `oc debug bc` with the image referenced to inspect the container environment (including Dockerfile in /root/buildinfo).

**Comment by pylejowdmn** [comment]
I'll have to test some things.  We ran into some issues with SSL and openjdk.  We ended up switching to the Oracle JDK and it cleared up our SSL issue.

**Comment by lpsantil** [comment]
If there is a bug, be sure to file a relevant report.  If you're not sure which project, open a Support Case, send me an email and I'll help you find the right people to address it.

**Comment by pylejowdmn** [comment]
Took a bit more round about that we wanted but we got it working.
